### ISSUE TITLE
Navigation hidden/not fitting on mobile devices

### ISSUE THREAD

**Issue by jschroeter** [gdoor-org/gdoor-org.github.io#1]
<img width="1491" src="https://github.com/gdoor-org/gdoor-org.github.io/assets/487046/a8808dd4-f8cd-42ad-acdf-71a49133e159">

I guess this CSS comes from the theme. Maybe it makes sense to check if there is a suitable more modern theme, the code looks a bit outdated (e.g. code targeting Internet Explorer < 8).
But great work to put this website together, thanks!

**Comment by DaSchaef** [comment]
Feel free to update/replace/change the template, it is a github default theme. I only changed the color to orange to match the logo a bit.  :sweat_smile: 

CSS can be overwritten, in assets/css or so. The theme name is in _config.yml

**Comment by jschroeter** [comment]
I pushed a workaround so the navigation is at least visible, but doesn't look nice yet. Maybe some of us has a bit of time to improve it in the future, so let's leave the issue open.

**Comment by DaSchaef** [comment]
I tried a new template, still pretty hacky setup, but should be better now.

**Comment by jschroeter** [comment]
Looks good, thanks!
